---
name: Release
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  # Builds the Dockerfile and pushes it to dockerhub and GHCR
  release:
    name: Release - Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current-date
        run: |
          echo "TODAY=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.current-date.outputs.TODAY }}
          flavor: latest=true

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}